package librarymanagement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author raman
 */
public class UserContents extends javax.swing.JFrame {

    /**
     * Creates new form userContents
     */
    public UserContents() {
        initComponents();
        MainPanel.setVisible(true);
SearchPanel.setVisible(false);
exploreBooks.setVisible(false);
VIEWFINE.setVisible(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        SidePanel = new javax.swing.JPanel();
        usercontentLabel = new javax.swing.JLabel();
        searchSideButton = new javax.swing.JButton();
        exploreBooksButton = new javax.swing.JButton();
        finesSideButton = new javax.swing.JButton();
        logoutSideButton = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchBookByTitle = new javax.swing.JButton();
        searcHBookByAuthor = new javax.swing.JButton();
        searchBookTitle = new javax.swing.JTextField();
        searchBookAuthor = new javax.swing.JTextField();
        submitSearchButton = new javax.swing.JButton();
        exploreBooks = new javax.swing.JPanel();
        BookmanagementLbel = new javax.swing.JLabel();
        viewAllBooksButton = new javax.swing.JButton();
        viewAvailableBooksButton = new javax.swing.JButton();
        returnBooksButton = new javax.swing.JButton();
        addBooktoWishlistButton = new javax.swing.JButton();
        removeBookFromWishListButton = new javax.swing.JButton();
        VIEWFINE = new javax.swing.JPanel();
        viewFineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 255, 204));
        SidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidePanelMouseClicked(evt);
            }
        });

        usercontentLabel.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        usercontentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usercontentLabel.setText("USER CONTENTS");
        usercontentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        searchSideButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        searchSideButton.setText("SEARCH");
        searchSideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchSideButtonMouseClicked(evt);
            }
        });
        searchSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSideButtonActionPerformed(evt);
            }
        });

        exploreBooksButton.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        exploreBooksButton.setText("EXPLORE BOOKS");
        exploreBooksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exploreBooksButtonMouseClicked(evt);
            }
        });
        exploreBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exploreBooksButtonActionPerformed(evt);
            }
        });

        finesSideButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        finesSideButton.setText("FINES");
        finesSideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finesSideButtonMouseClicked(evt);
            }
        });
        finesSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finesSideButtonActionPerformed(evt);
            }
        });

        logoutSideButton.setBackground(new java.awt.Color(255, 204, 204));
        logoutSideButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        logoutSideButton.setText("LOG OUT");
        logoutSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutSideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exploreBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchSideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finesSideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(usercontentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutSideButton)
                .addGap(91, 91, 91))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(usercontentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(searchSideButton)
                .addGap(48, 48, 48)
                .addComponent(exploreBooksButton)
                .addGap(55, 55, 55)
                .addComponent(finesSideButton)
                .addGap(46, 46, 46)
                .addComponent(logoutSideButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 500));

        MainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainPanelMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg3.jpg"))); // NOI18N

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 0, 560, 500));

        SearchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchPanelMouseClicked(evt);
            }
        });

        searchLabel.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchLabel.setText("SEARCH");
        searchLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        searchBookByTitle.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        searchBookByTitle.setText("SEARCH BOOK BY TITLE");
        searchBookByTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookByTitleActionPerformed(evt);
            }
        });

        searcHBookByAuthor.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        searcHBookByAuthor.setText("SEARCH BOOK BY AUTHOR");

        submitSearchButton.setBackground(new java.awt.Color(204, 255, 204));
        submitSearchButton.setFont(new java.awt.Font("Kristen ITC", 3, 12)); // NOI18N
        submitSearchButton.setText("SUBMIT");
        submitSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBookAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(searchBookTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBookByTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searcHBookByAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitSearchButton)
                .addGap(62, 62, 62))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBookByTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(searchBookTitle))
                .addGap(56, 56, 56)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searcHBookByAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(submitSearchButton)
                .addGap(40, 40, 40))
        );

        getContentPane().add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 560, 500));

        exploreBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exploreBooksMouseClicked(evt);
            }
        });

        BookmanagementLbel.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        BookmanagementLbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookmanagementLbel.setText("Explore books");

        viewAllBooksButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        viewAllBooksButton.setText("VIEW ALL BOOKS");

        viewAvailableBooksButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        viewAvailableBooksButton.setText("VIEW AVAILABLE BOOKS");

        returnBooksButton.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        returnBooksButton.setText("RETURN BOOK");

        addBooktoWishlistButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        addBooktoWishlistButton.setText("ADD BOOK TO WISHLIST");

        removeBookFromWishListButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        removeBookFromWishListButton.setText("REMOVE BOOK FROM WISHLIST");
        removeBookFromWishListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookFromWishListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exploreBooksLayout = new javax.swing.GroupLayout(exploreBooks);
        exploreBooks.setLayout(exploreBooksLayout);
        exploreBooksLayout.setHorizontalGroup(
            exploreBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exploreBooksLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(exploreBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBooktoWishlistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnBooksButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAvailableBooksButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAllBooksButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, exploreBooksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removeBookFromWishListButton)))
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exploreBooksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BookmanagementLbel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        exploreBooksLayout.setVerticalGroup(
            exploreBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exploreBooksLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BookmanagementLbel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewAllBooksButton)
                .addGap(52, 52, 52)
                .addComponent(viewAvailableBooksButton)
                .addGap(47, 47, 47)
                .addComponent(returnBooksButton)
                .addGap(43, 43, 43)
                .addComponent(addBooktoWishlistButton)
                .addGap(40, 40, 40)
                .addComponent(removeBookFromWishListButton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(exploreBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 560, 500));

        VIEWFINE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VIEWFINEMouseClicked(evt);
            }
        });

        viewFineButton.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        viewFineButton.setText("View Fine");
        viewFineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VIEWFINELayout = new javax.swing.GroupLayout(VIEWFINE);
        VIEWFINE.setLayout(VIEWFINELayout);
        VIEWFINELayout.setHorizontalGroup(
            VIEWFINELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(VIEWFINELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VIEWFINELayout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(viewFineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(170, 170, 170)))
        );
        VIEWFINELayout.setVerticalGroup(
            VIEWFINELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(VIEWFINELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(VIEWFINELayout.createSequentialGroup()
                    .addGap(239, 239, 239)
                    .addComponent(viewFineButton)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        getContentPane().add(VIEWFINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSideButtonActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(false);
SearchPanel.setVisible(true);
exploreBooks.setVisible(false);
VIEWFINE.setVisible(false);
    }//GEN-LAST:event_searchSideButtonActionPerformed

    private void searchBookByTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookByTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBookByTitleActionPerformed

    private void removeBookFromWishListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookFromWishListButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBookFromWishListButtonActionPerformed

    private void searchSideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchSideButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchSideButtonMouseClicked

    private void exploreBooksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exploreBooksButtonMouseClicked
        // TODO add your handling code here:
//        
    }//GEN-LAST:event_exploreBooksButtonMouseClicked

    private void finesSideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finesSideButtonMouseClicked
        // TODO add your handling code here:
//        
    }//GEN-LAST:event_finesSideButtonMouseClicked

    private void SidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidePanelMouseClicked

        
    }//GEN-LAST:event_SidePanelMouseClicked

    private void MainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainPanelMouseClicked
    }//GEN-LAST:event_MainPanelMouseClicked

    private void SearchPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchPanelMouseClicked

    private void exploreBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exploreBooksMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_exploreBooksMouseClicked

    private void VIEWFINEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWFINEMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VIEWFINEMouseClicked

    private void logoutSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutSideButtonActionPerformed
        // TODO add your handling code here:
        MainPage MainPage=new MainPage();
        MainPage.setVisible(true);
        MainPage.pack();
        MainPage.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_logoutSideButtonActionPerformed

    private void exploreBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreBooksButtonActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(false);
SearchPanel.setVisible(false);
exploreBooks.setVisible(true);
VIEWFINE.setVisible(false);
    }//GEN-LAST:event_exploreBooksButtonActionPerformed

    private void finesSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finesSideButtonActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(false);
SearchPanel.setVisible(false);
exploreBooks.setVisible(false);
VIEWFINE.setVisible(true);
    }//GEN-LAST:event_finesSideButtonActionPerformed

    private void submitSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitSearchButtonActionPerformed

    private void viewFineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFineButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userContents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userContents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userContents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userContents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserContents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookmanagementLbel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel VIEWFINE;
    private javax.swing.JButton addBooktoWishlistButton;
    private javax.swing.JPanel exploreBooks;
    private javax.swing.JButton exploreBooksButton;
    private javax.swing.JButton finesSideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton logoutSideButton;
    private javax.swing.JButton removeBookFromWishListButton;
    private javax.swing.JButton returnBooksButton;
    private javax.swing.JButton searcHBookByAuthor;
    private javax.swing.JTextField searchBookAuthor;
    private javax.swing.JButton searchBookByTitle;
    private javax.swing.JTextField searchBookTitle;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton searchSideButton;
    private javax.swing.JButton submitSearchButton;
    private javax.swing.JLabel usercontentLabel;
    private javax.swing.JButton viewAllBooksButton;
    private javax.swing.JButton viewAvailableBooksButton;
    private javax.swing.JButton viewFineButton;
    // End of variables declaration//GEN-END:variables
}
